// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeSystem.Context;

namespace SmartHomeSystem.Migrations
{
    [DbContext(typeof(SmartHomeSystemDBContext))]
    [Migration("20210314112307_EmailAndPassword")]
    partial class EmailAndPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartHomeSystem.Models.Archive", b =>
                {
                    b.Property<int>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedValueId")
                        .HasColumnType("int");

                    b.HasKey("ArchiveId");

                    b.HasIndex("UpdatedDeviceId");

                    b.HasIndex("UpdatedValueId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.AvailableVals", b =>
                {
                    b.Property<int>("AvailableValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("AvailableValuesId");

                    b.ToTable("AvailableVals");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DPCurrentValue")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceHomeHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("DPCurrentValue");

                    b.HasIndex("DeviceHomeHomeId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DeviceParameterCurrentValue", b =>
                {
                    b.Property<int>("DeviceParamCurrentValId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("DeviceParamCurrentValId");

                    b.ToTable("DeviceParameterCurrentValues");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DeviceType", b =>
                {
                    b.Property<int>("DeviceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DeviceTypeId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DeviceTypeAvailableValues", b =>
                {
                    b.Property<int>("DeviceTypeAvailableValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailableValsId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.HasKey("DeviceTypeAvailableValuesId");

                    b.HasIndex("AvailableValsId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("DeviceTypeAvailableValues");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DevicesCurrentValues", b =>
                {
                    b.Property<int>("DevicesCurrentValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceParameterCurrentValueId")
                        .HasColumnType("int");

                    b.HasKey("DevicesCurrentValuesId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceParameterCurrentValueId");

                    b.ToTable("DevicesCurrentValues");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.Home", b =>
                {
                    b.Property<int>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.HasKey("HomeId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.NumberParameter", b =>
                {
                    b.Property<int>("NumberParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("NumberParameterId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("NumberParameters");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.StringParameter", b =>
                {
                    b.Property<int>("StringParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLimitedToAvailableValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("StringParameterId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("StringParameters");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.UserHome", b =>
                {
                    b.Property<int>("UserHomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserHomeId");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHomes");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.Archive", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.Device", "UpdatedDevice")
                        .WithMany("Archives")
                        .HasForeignKey("UpdatedDeviceId");

                    b.HasOne("SmartHomeSystem.Models.DeviceParameterCurrentValue", "UpdatedValue")
                        .WithMany("Archives")
                        .HasForeignKey("UpdatedValueId");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.Device", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.DeviceParameterCurrentValue", "Device_Parameter_Current_Value")
                        .WithMany("Devices")
                        .HasForeignKey("DPCurrentValue");

                    b.HasOne("SmartHomeSystem.Models.Home", "DeviceHome")
                        .WithMany("DevicesInHome")
                        .HasForeignKey("DeviceHomeHomeId");

                    b.HasOne("SmartHomeSystem.Models.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DeviceTypeAvailableValues", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.AvailableVals", null)
                        .WithMany("DeviceTypeAvailableValues")
                        .HasForeignKey("AvailableValsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeSystem.Models.DeviceType", null)
                        .WithMany("DeviceTypeAvailableValues")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHomeSystem.Models.DevicesCurrentValues", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.Device", null)
                        .WithMany("DevicesCurrentValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeSystem.Models.DeviceParameterCurrentValue", null)
                        .WithMany("DevicesCurrentValues")
                        .HasForeignKey("DeviceParameterCurrentValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHomeSystem.Models.Home", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.User", "Owner")
                        .WithMany("Home")
                        .HasForeignKey("OwnerUserId");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.NumberParameter", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.DeviceType", "DeviceType")
                        .WithMany("NumberParametersForDeviceType")
                        .HasForeignKey("DeviceTypeId");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.StringParameter", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.DeviceType", "DeviceType")
                        .WithMany("StringParametersForDeviceType")
                        .HasForeignKey("DeviceTypeId");
                });

            modelBuilder.Entity("SmartHomeSystem.Models.UserHome", b =>
                {
                    b.HasOne("SmartHomeSystem.Models.Home", null)
                        .WithMany("UserHome")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeSystem.Models.User", null)
                        .WithMany("UserHome")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
